# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Build required apk and test apk for screengrab command"
  lane :buildtest do
    gradle(
      task: "assembleDebug",
      print_command: true,
      flags: "-Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000"
    )

    gradle(task: "assembleDebugAndroidTest",
      print_command: true,
      flags: "-Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000"
    )

  end

  desc "Runs all the tests with coverage"
  lane :alltests do
    gradle(task: "jacocoCoverage",
      print_command: true,
      flags: "-Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000"
    )
  end

  desc "Runs Small QA flavor tests with coverage"
  lane :smalltests do
    gradle(task: "createDebugCoverageReport",
      print_command: true,
      flags: "-Pandroid.testInstrumentationRunnerArguments.size=small -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000"
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
